/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mondooSidebar: [
    {
      type: "doc",
      id: "platform/home",
      label: "Mondoo Platform Home",
    },
    {
      type: "category",
      label: "Get Started",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "platform/start",
        },
      ],
    },
    {
      type: "category",
      label: "Integrate Your Assets",
      items: [
        {
          type: "category",
          label: "Cloud",
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "platform/infra/cloud/overview",
              label: "Overview",
            },
            {
              type: "doc",
              id: "platform/infra/cloud/azure/overview",
              label: "Azure",
            },
            {
              type: "autogenerated",
              dirName: "platform/infra/cloud/aws",
            },
            {
              type: "autogenerated",
              dirName: "platform/infra/cloud/gcp",
            },
            {
              type: "autogenerated",
              dirName: "platform/infra/cloud/kubernetes",
            },
            {
              type: "doc",
              id: "platform/infra/cloud/oci",
              label: "Oracle Cloud Infrastructure",
            },
            {
              type: "doc",
              id: "platform/infra/cloud/vmware",
              label: "VMware",
            },
          ],
        },
        {
          type: "category",
          label: "SaaS",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "platform/infra/saas",
            },
          ],
        },
        {
          type: "category",
          label: "Networking",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "platform/infra/networking",
            },
          ],
        },
        {
          type: "category",
          label: "Servers and Endpoints",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "platform/infra/opsys",
            },
          ],
        },
        {
          type: "category",
          label: "Supply Chain",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "platform/infra/supply",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Security",
      items: [
        {
          type: "autogenerated",
          dirName: "platform/security",
        },
      ],
    },
    {
      type: "category",
      label: "Compliance",
      items: [
        {
          type: "autogenerated",
          dirName: "platform/compliance",
        },
      ],
    },
    {
      type: "category",
      label: "Asset Intelligence",
      items: [
        {
          type: "autogenerated",
          dirName: "platform/intel",
        },
      ],
    },
    {
      type: "category",
      label: "Manage Mondoo",
      items: [
        {
          type: "autogenerated",
          dirName: "platform/maintain",
        },
      ],
    },
    {
      type: "doc",
      id: "glossary",
      label: "Glossary of Terms",
    },
    {
      type: "link",
      label: "Releases",
      href: "/releases/",
    },
  ],

  // ************* Azure Azure Azure Azure Azure Azure Azure Azure *****************

  Azure: [
    {
      type: "category",
      label: "Azure Integration Setup Guide",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "platform/infra/cloud/azure/continuous", // Generate sidebar slice
        },
      ],
    },
  ],

  // ************* MQL MQL MQL MQL MQL MQL MQL MQL MQL MQL MQL MQL *****************

  MQL: [
    {
      type: "category",
      label: "MQL",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "mql", // Generate sidebar slice
        },
      ],
    },
  ],

  // ************* cnQUERY cnQUERY cnQUERY cnQUERY cnQUERY  *****************

  cnquery: [
    {
      type: "doc",
      id: "cnquery/home",
      label: "cnquery Docs Home",
    },
    {
      type: "doc",
      id: "cnquery/cnquery-about",
      label: "What Is cnquery?",
    },
    {
      type: "doc",
      id: "cnquery/cnquery-get-started",
      label: "Get Started with cnquery",
    },
    {
      type: "category",
      label: "Query Your Systems",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "AWS",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cnquery/cnquery-aws", // Generate sidebar slice
            },
          ],
        },
        {
          type: "doc",
          id: "cnquery/cnquery-azure/cnquery-azure-intro",
          label: "Azure",
        },
        {
          type: "doc",
          id: "cnquery/cnquery-gcp/cnquery-gcp-intro",
          label: "GCP",
        },
        {
          type: "category",
          label: "Kubernetes",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cnquery/cnquery-k8s", // Generate sidebar slice
            },
          ],
        },
        {
          type: "doc",
          id: "cnquery/cnquery-oper/cnquery-linux-intro",
          label: "Linux",
        },
        {
          type: "doc",
          id: "cnquery/cnquery-oper/cnquery-macos-intro",
          label: "macOS",
        },
        {
          type: "doc",
          id: "cnquery/cnquery-oper/cnquery-windows-intro",
          label: "Windows",
        },
        {
          type: "category",
          label: "SaaS",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cnquery/saas", // Generate sidebar slice
            },
          ],
        },
      ],
    },
    {
      type: "doc",
      id: "cnquery/cnquery-platform",
      label: "Log into Mondoo Platform for More",
    },
    {
      type: "doc",
      id: "cnquery/cnquery-query",
      label: "Query Your Infrastructure",
    },
    {
      type: "doc",
      id: "cnquery/cnquery-run-pack",
      label: "Run a Query Pack",
    },
    {
      type: "doc",
      id: "cnquery/providers",
      label: "Manage cnquery Providers",
    },
    {
      type: "doc",
      id: "cnquery/cnquery-supported",
      label: "Supported Scan Targets",
    },
    {
      type: "category",
      label: "CLI Commands",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "cnquery/cli", // Generate sidebar slice
        },
      ],
    },
  ],

  // ************* cnSPEC cnSPEC  cnSPEC  cnSPEC  cnSPEC   *****************

  cnspec: [
    {
      type: "doc",
      id: "cnspec/home",
      label: "cnspec Docs Home",
    },
    {
      type: "doc",
      id: "cnspec/cnspec-about",
      label: "What Is cnspec?",
    },
    {
      type: "doc",
      id: "cnspec/cnspec-get-started",
      label: "Get Started with cnspec",
    },
    {
      type: "category",
      label: "Extended Installation Options",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "cnspec/cnspec-adv-install", // Generate sidebar slice
        },
      ],
    },
    {
      type: "category",
      label: "Assess System Security",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Cloud",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cnspec/cloud", // Generate sidebar slice
            },
          ],
        },
        {
          type: "category",
          label: "Operating Systems",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cnspec/cnspec-oper", // Generate sidebar slice
            },
          ],
        },
        {
          type: "category",
          label: "SaaS",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cnspec/saas", // Generate sidebar slice
            },
          ],
        },
        {
          type: "category",
          label: "Supply Chain",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cnspec/supplychain", // Generate sidebar slice
            },
          ],
        },
      ],
    },
    {
      type: "doc",
      id: "cnspec/results",
      label: "Report Results",
    },
    {
      type: "doc",
      id: "cnspec/cnspec-platform",
      label: "Log into Mondoo Platform for More",
    },
    {
      type: "category",
      label: "Policies",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "cnspec/cnspec-policies", // Generate sidebar slice
        },
      ],
    },
    {
      type: "doc",
      id: "cnspec/cnspec-scan",
      label: "Create Checks in cnspec shell",
    },
    {
      type: "doc",
      id: "cnspec/cnspec-supported",
      label: "Supported Scan Targets",
    },
    {
      type: "category",
      label: "CLI Commands",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "cnspec/cli", // Generate sidebar slice
        },
      ],
    },
    {
      type: "doc",
      id: "cnspec/uninstall",
      label: "Uninstall cnspec",
    },
  ],
};
